#!/bin/sh
xmodmap "/home/dilks/.Xmodmap"
GSDPID=`pidof gnome-settings-daemon`
if [ "x$GSDPID" == "x" ]; then
  gnome-settings-daemon &
fi
xrdb -merge ~/.Xdefaults  
synclient MaxTapTime=0
xcompmgr -f -D 3 &
#fbsetbg -l
nitrogen --restore &
xscreensaver -nosplash &
pulseaudio &
gkrellm &
nm-applet &
exec fluxbox
