[built-in options]
pkg_config_path = ['/home/dilks/j/install/lib/pkgconfig']
; core
buildtype = 'debug'
prefix = '~/j/iguana/install-san'
; tests
test_data_file = '~/j/iguana/data.hipo'
test_output_dir = '~/j/iguana/tmp'
test_validator_all_stats = True
; project options
bind_fortran = True
bind_python = True
install_examples = True
install_documentation = True
z_require_root = True
; sanitizer stuff
b_sanitize = 'thread'
b_lundef = False
b_pie = True
test_num_threads= 8
test_multithreading = 'enabled'
; subproject options
[rcdb:built-in options]
home = '~/j/rcdb'
[binaries]
c = '/usr/bin/clang'
cpp = '/usr/bin/clang++'
