[built-in options]
; core
buildtype = 'debug'
prefix = '~/j/iguana/install-image'
; tests
test_data_file = '~/j/iguana/data.hipo'
test_output_dir = '~/j/iguana/tmp'
test_validator_all_stats = True
; project options
bind_fortran = True
bind_python = True
install_examples = True
install_documentation = True
test_xcheckalgo = 'enabled'
[binaries]
c = '/usr/bin/gcc'
cpp = '/usr/bin/g++'
